import { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { AlertTriangle, ArrowRight, Bell, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, FileCheck2, Filter, IndianRupee, MapPin, Package, Pencil, Search, Settings, Truck, UserRound, Wallet, X } from 'lucide-react';
import { BarChart, Bar, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import useAuthStore from '../../store/authStore';
import LanguageSelector from '../../components/LanguageSelector';
import dashboardData from './dashboardData';

const money=n=>`₹${Number(n).toLocaleString('en-IN')}`;
const Pill=({children,kind=''})=><span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${kind==='paid'?'bg-emerald-50 text-emerald-700':kind==='pending'?'bg-amber-50 text-amber-700':'bg-[var(--accent)] text-[var(--primary)]'}`}>{children}</span>;
const Section=({title,subtitle,action})=><div className="mb-3 flex items-end justify-between gap-3"><div><h2 className="text-lg font-semibold">{title}</h2>{subtitle&&<p className="mt-1 text-sm text-[var(--muted)]">{subtitle}</p>}</div>{action}</div>;

export default function RecyclerDashboard(){
 const navigate=useNavigate(); const user=useAuthStore(s=>s.user); const [q,setQ]=useState(''); const [filter,setFilter]=useState('All'); const [selected,setSelected]=useState(null); const [offer,setOffer]=useState(''); const [sent,setSent]=useState([]); const [showRates,setShowRates]=useState(false); const [rates,setRates]=useState(dashboardData.rates); const [editing,setEditing]=useState(null);
 const [paymentMethod,setPaymentMethod]=useState('');
 const [selectedPayment,setSelectedPayment]=useState(null);
 const [paidPayments,setPaidPayments]=useState([]);
 const [handoverWeight,setHandoverWeight]=useState('');
 const [handoverMaterial,setHandoverMaterial]=useState('');
 const [intakeStages,setIntakeStages]=useState({
  Received:126,
  Sorted:94,
  Processing:61,
  'Completed / Recycled':39
});
 const [handoverValue,setHandoverValue]=useState('');
 const [handoverPhoto,setHandoverPhoto]=useState(null);
 const [verifiedHandovers,setVerifiedHandovers]=useState([]);
 const materials=useMemo(()=>['All',...new Set(dashboardData.lots.map(x=>x.material))],[]);
 const lots=useMemo(()=>dashboardData.lots.filter(x=>(filter==='All'||x.material===filter)&&(!q||`${x.referenceId} ${x.material} ${x.location}`.toLowerCase().includes(q.toLowerCase()))),[q,filter]);
 const sendOffer=()=>{if(selected&&Number(offer)>0){setSent(v=>[...v,selected.id]);setSelected(null);setOffer('')}};
 const saveRate=(id,value)=>{setRates(v=>v.map(x=>x.id===id?{...x,price:Number(value)||0}:x));setEditing(null)};
 const verifyHandover=()=>{
  if(!selected||selected.type!=='handover') return;

  if(!handoverWeight||!handoverMaterial||!handoverValue){
    alert('Please fill actual weight, material and final value.');
    return;
  }

  setVerifiedHandovers(v=>[...v,selected.id]);
  setSelected(null);
  setHandoverWeight('');
  setHandoverMaterial('');
  setHandoverValue('');
  setHandoverPhoto(null);

  alert('Handover verified successfully.');
};
const makePayment=()=>{
  if(!selectedPayment||!paymentMethod) return;

  setPaidPayments(v=>[...v,selectedPayment.id]);
  setSelectedPayment(null);
  setPaymentMethod('');

  alert('Payment marked as paid successfully.');
};
const updateIntakeStage=(fromStage,toStage,amount)=>{
  const qty=Number(amount);

  if(!qty||qty<=0){
    alert('Enter a valid quantity.');
    return;
  }

  if(intakeStages[fromStage]<qty){
    alert(`Only ${intakeStages[fromStage]} kg is available in ${fromStage}.`);
    return;
  }

  setIntakeStages(prev=>({
    ...prev,
    [fromStage]:prev[fromStage]-qty,
    [toStage]:prev[toStage]+qty
  }));

  alert(`${qty} kg moved from ${fromStage} to ${toStage}.`);
};
 return <div className="min-h-screen bg-[var(--background)] text-[var(--foreground)]"><main className="mx-auto w-full max-w-7xl px-4 pb-28 pt-5 sm:px-6 lg:px-8 lg:pb-10">
  <header className="flex items-center justify-between gap-4"><div className="min-w-0"><p className="text-sm text-[var(--muted)]">Welcome</p><h1 className="mt-1 truncate text-[clamp(1.5rem,5vw,2rem)] font-semibold">{user?.firstName||'Recycler'}</h1><p className="mt-1 text-sm text-[var(--muted)]">Recycler procurement dashboard</p></div><div className="flex items-center gap-2"><LanguageSelector/><button onClick={()=>navigate('/recycler/settings')} className="flex h-11 w-11 items-center justify-center rounded-full border border-[var(--border)] bg-[var(--surface)] text-[var(--muted)]"><Settings size={19}/></button></div></header>
  <div className="mt-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-900"><AlertTriangle size={19} className="mt-0.5"/><div className="flex-1"><b>3 nearby lots need your attention</b><p className="mt-1 text-sm opacity-80">Review available material and submit quotations before offers expire.</p></div></div>
  <section className="mt-7 rounded-[30px] bg-[var(--primary)] p-5 text-white shadow-[0_16px_40px_rgba(0,0,0,.08)] sm:p-7"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><div className="mb-4 flex h-11 w-11 items-center justify-center rounded-2xl bg-white/15"><Package size={21}/></div><h2 className="text-2xl font-semibold">Incoming E-Waste Lots</h2><p className="mt-1 text-sm opacity-70">Discover collector lots, compare value and send quotations.</p></div><button onClick={()=>document.getElementById('marketplace')?.scrollIntoView({behavior:'smooth'})} className="flex items-center justify-center gap-2 rounded-2xl bg-white px-5 py-3 text-sm font-semibold text-[var(--primary)]">Browse marketplace <ArrowRight size={17}/></button></div></section>
  <section className="mt-7 grid grid-cols-2 gap-3 md:grid-cols-3 xl:grid-cols-6">{[['Available Lots',dashboardData.summary.availableLots,Package],['Requests',dashboardData.summary.incomingRequests,Bell],['Pickups',dashboardData.summary.activePickups,Truck],['Handovers',dashboardData.summary.pendingHandovers,FileCheck2],['Pending Pay',money(dashboardData.summary.pendingPayments),Wallet],["Today's Intake",`${dashboardData.summary.todayIntake} kg`,CircleDollarSign]].map(([l,v,I])=><div key={l} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[var(--accent)] text-[var(--primary)]"><I size={18}/></div><p className="mt-4 text-2xl font-semibold">{v}</p><p className="mt-1 text-xs text-[var(--muted)]">{l}</p></div>)}</section>
  <section className="mt-8"><Section title="Quick Actions"/><div className="grid grid-cols-2 gap-3 md:grid-cols-4">{[['Browse Lots',Package,'marketplace'],['Manage Rates',IndianRupee,'rates'],['Pickup Management',Truck,'pickups'],['Payments',Wallet,'payments']].map(([l,I,id])=><button key={l} onClick={()=>id==='rates'?setShowRates(true):document.getElementById(id)?.scrollIntoView({behavior:'smooth'})} className="flex items-center gap-3 rounded-2xl border border-[var(--border)] bg-[var(--surface)] p-4 text-left transition hover:-translate-y-0.5"><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-[var(--accent)] text-[var(--primary)]"><I size={18}/></span><b className="text-sm">{l}</b></button>)}</div></section>
  <section id="marketplace" className="mt-8"><Section title="Incoming Lot Marketplace" subtitle="Lots currently available for procurement" action={<span className="text-sm text-[var(--muted)]">{lots.length} lots</span>}/><div className="mb-4 flex flex-col gap-3 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-[var(--muted)]" size={18}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search lot ID, material or location" className="w-full rounded-2xl border border-[var(--border)] bg-[var(--surface)] py-3 pl-10 pr-4 text-sm outline-none"/></div><div className="flex items-center gap-2 overflow-x-auto"><Filter size={17}/>{materials.map(m=><button key={m} onClick={()=>setFilter(m)} className={`whitespace-nowrap rounded-full px-4 py-2 text-xs font-semibold ${filter===m?'bg-[var(--primary)] text-white':'border border-[var(--border)] bg-[var(--surface)] text-[var(--muted)]'}`}>{m}</button>)}</div></div><div className="grid gap-4 lg:grid-cols-2">{lots.map(l=><article key={l.id} className="rounded-[26px] border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex justify-between gap-3"><div><p className="text-xs text-[var(--muted)]">{l.referenceId}</p><h3 className="mt-1 text-lg font-semibold">{l.material}</h3></div><Pill>Available</Pill></div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-[var(--surface-soft)] p-3"><small className="text-[var(--muted)]">Weight</small><p className="mt-1 font-semibold">{l.weight} kg</p></div><div className="rounded-2xl bg-[var(--surface-soft)] p-3"><small className="text-[var(--muted)]">Estimated value</small><p className="mt-1 font-semibold">{money(l.weight*l.rate)}</p></div></div><p className="mt-4 flex items-center gap-2 text-sm text-[var(--muted)]"><MapPin size={16}/>{l.location} · {l.distance}</p><div className="mt-4 flex items-center justify-between border-t border-[var(--border)] pt-4"><div><small className="text-[var(--muted)]">Collector</small><p className="text-sm font-semibold">{l.collector}</p></div>{sent.includes(l.id)?<Pill kind="pending">Offer sent</Pill>:<button onClick={()=>setSelected(l)} className="flex items-center gap-1 rounded-xl bg-[var(--primary)] px-4 py-2.5 text-sm font-semibold text-white">Submit offer <ChevronRight size={16}/></button>}</div></article>)}</div></section>
  <section className="mt-8"><Section title="Smart Lot Recommendations" subtitle="Prioritized using material, quantity, location, price and pickup capability"/><div className="grid gap-4 md:grid-cols-3">{dashboardData.lots.slice(0,3).map((l,i)=><div key={l.id} className="rounded-[26px] border border-[var(--border)] bg-[var(--surface)] p-5"><div className="flex justify-between"><b>{l.material}</b><span className="text-xs font-semibold text-[var(--primary)]">{96-i*5}% match</span></div><p className="mt-5 text-2xl font-semibold">{l.weight} kg</p><p className="text-sm text-[var(--muted)]">{l.location}</p><div className="mt-4 space-y-1 text-xs text-[var(--muted)]"><p>✓ Fits service area</p><p>✓ Pickup available</p><p>✓ Current rate: {money(l.rate)}/kg</p></div><button onClick={()=>setSelected(l)} className="mt-5 w-full rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold">Review lot →</button></div>)}</div></section>
  <section id="rates" className="mt-8"><Section title="Buying Rates" subtitle="Rates published for your service area" action={<button onClick={()=>setShowRates(true)} className="text-sm font-semibold text-[var(--primary)]">Manage</button>}/><div className="grid grid-cols-2 gap-3 sm:grid-cols-4">{rates.map(r=><div key={r.id} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4"><p className="text-sm text-[var(--muted)]">{r.material}</p><p className="mt-5 text-2xl font-semibold">{money(r.price)}</p><p className="text-xs text-[var(--muted)]">per kg</p><button onClick={()=>setShowRates(true)} className="mt-3 flex gap-1 text-xs font-semibold text-[var(--primary)]"><Pencil size={13}/> Update</button></div>)}</div></section>
  <section id="pickups" className="mt-8 grid gap-8 lg:grid-cols-2"><div><Section title="Pickup Management" subtitle="Upcoming collection tasks"/><div className="space-y-3">{dashboardData.pickups.map(p=><div key={p.id} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex justify-between"><div><small className="text-[var(--muted)]">{p.lotId}</small><p className="font-semibold">{p.material} · {p.weight} kg</p></div><Pill>{p.status}</Pill></div><p className="mt-4 flex gap-2 text-sm text-[var(--muted)]"><Clock3 size={15}/>{p.date} · {p.time}</p><p className="mt-2 flex gap-2 text-sm text-[var(--muted)]"><MapPin size={15}/>{p.location}</p></div>)}</div></div><div><Section title="Handover Verification" subtitle="Lots waiting for final verification"/><div className="space-y-3">{dashboardData.handovers.map(h=><div key={h.id} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4"><div className="flex justify-between"><div><small className="text-[var(--muted)]">{h.referenceId}</small><p className="font-semibold">{h.material}</p></div>{verifiedHandovers.includes(h.id)?<Pill kind="paid">Verified</Pill>:<Pill kind="pending">Pending</Pill>}</div><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><div>Weight<br/><b>{h.weight} kg</b></div><div>Final value<br/><b>{money(h.value)}</b></div></div><button onClick={()=>setSelected({type:'handover',...h})} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold">{!verifiedHandovers.includes(h.id)&&<button onClick={()=>{setHandoverWeight(String(h.weight));setHandoverMaterial(h.material);setHandoverValue(String(h.value));setSelected({type:'handover',...h})}} className="mt-4 flex w-full items-center justify-center gap-2 rounded-xl border border-[var(--border)] px-4 py-2.5 text-sm font-semibold">Verify handover <CheckCircle2 size={16}/></button>}</button></div>)}</div></div></section>
  <section id="payments" className="mt-8 grid gap-8 lg:grid-cols-2"><div><Section title="Payment Management" subtitle="Recent and pending supplier payments"/><div className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)]">{dashboardData.payments.map(p=><div key={p.id} className="flex items-center justify-between gap-3 border-b border-[var(--border)] p-4 last:border-0"><div className="flex gap-3"><CircleDollarSign className="text-[var(--primary)]"/><div><b className="text-sm">{p.collector}</b><p className="text-xs text-[var(--muted)]">{p.lotId} · {p.method}</p></div></div><div className="text-right"><b>{money(p.amount)}</b><br/>{paidPayments.includes(p.id)||p.status==='Paid'?<Pill kind="paid">Paid</Pill>:<button onClick={()=>setSelectedPayment(p)} className="mt-1 rounded-lg bg-[var(--primary)] px-3 py-1.5 text-xs font-semibold text-white">Make Payment</button>}</div></div>)}</div></div><div><Section title="Material Intake" subtitle="Current processing pipeline"/><div className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5 space-y-5">{dashboardData.intake.map(([l,v,p])=><div key={l}><div className="mb-2 flex justify-between text-sm"><b>{l}</b><span>{v} kg</span></div><div className="h-2 rounded-full bg-[var(--surface-soft)]"><div className="h-2 rounded-full bg-[var(--primary)]" style={{width:`${p}%`}}/></div></div>)}</div></div></section>
  <section className="mt-8 grid gap-8 lg:grid-cols-5"><div className="lg:col-span-2"><Section title="Inventory / Supply" subtitle="Received material available for planning"/><div className="grid grid-cols-2 gap-3">{dashboardData.inventory.map(([m,w,c])=><div key={m} className="rounded-[22px] border border-[var(--border)] bg-[var(--surface)] p-4"><p className="text-sm text-[var(--muted)]">{m}</p><p className="mt-3 text-2xl font-semibold">{w} kg</p><p className="mt-1 text-xs text-[var(--primary)]">{c}</p></div>)}</div></div><div className="lg:col-span-3"><Section title="Procurement Analytics" subtitle="Material intake over the last 7 days"/><div className="h-[300px] rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-4"><ResponsiveContainer width="100%" height="100%"><BarChart data={dashboardData.analytics.map(([day,kg])=>({day,kg}))}><CartesianGrid strokeDasharray="3 3" opacity={.25}/><XAxis dataKey="day"/><YAxis/><Tooltip/><Bar dataKey="kg" fill="var(--primary)" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></div></div></section>
  <section className="mt-8 grid gap-4 md:grid-cols-3">{[[FileCheck2,'Traceability Records','Track lot, quotation, final value, weight, handover and confirmation evidence.'],[Bell,'Supply Alerts','Receive relevant nearby lot and material availability notifications.'],[AlertTriangle,'Dispute Support','Review shared records for price, weight, payment or handover disputes.']].map(([I,t,d])=><div key={t} className="rounded-[24px] border border-[var(--border)] bg-[var(--surface)] p-5"><I className="text-[var(--primary)]" size={21}/><h3 className="mt-4 font-semibold">{t}</h3><p className="mt-1 text-sm text-[var(--muted)]">{d}</p><button className="mt-4 text-sm font-semibold text-[var(--primary)]">View →</button></div>)}</section>
  <p className="mt-8 text-center text-xs text-[var(--muted)]">Dashboard interactions currently use demo data. Backend endpoints are required to persist quotations, pickups, payments, intake and disputes.</p>
 </main>
 {selected&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-4 sm:items-center"><div className="w-full max-w-md rounded-[28px] bg-[var(--surface)] p-5"><div className="flex justify-between"><div><small className="text-[var(--muted)]">{selected.referenceId}</small><h3 className="text-xl font-semibold">{selected.material} · {selected.weight} kg</h3></div><button onClick={()=>setSelected(null)}><X/></button></div>{selected.type==='handover'?<><div className="mt-5 rounded-2xl bg-[var(--surface-soft)] p-4"><small>Final value</small><p className="text-2xl font-semibold">₹{Number(selected.value).toLocaleString('en-IN')}</p></div><label className="mt-5 block text-sm font-semibold">Actual weight (kg)<input type="number" value={handoverWeight} onChange={e=>setHandoverWeight(e.target.value)} placeholder="Enter actual weight" className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 outline-none"/></label><label className="mt-4 block text-sm font-semibold">Verified material<input type="text" value={handoverMaterial} onChange={e=>setHandoverMaterial(e.target.value)} placeholder={selected.material} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 outline-none"/></label><label className="mt-4 block text-sm font-semibold">Final value (₹)<input type="number" value={handoverValue} onChange={e=>setHandoverValue(e.target.value)} placeholder={selected.value} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 outline-none"/></label><label className="mt-4 block text-sm font-semibold">Verification photo<input type="file" accept="image/*" onChange={e=>setHandoverPhoto(e.target.files?.[0]||null)} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 text-sm"/></label>{handoverPhoto&&<p className="mt-2 text-xs text-[var(--muted)]">{handoverPhoto.name}</p>}<button onClick={verifyHandover} className="mt-5 w-full rounded-2xl bg-[var(--primary)] p-3 font-semibold text-white">Verify handover</button></>:<><div className="mt-5 rounded-2xl bg-[var(--surface-soft)] p-4"><small>Estimated value</small><p className="text-2xl font-semibold">{money(selected.weight*selected.rate)}</p></div><label className="mt-5 block text-sm font-semibold">Your quotation<input type="number" value={offer} onChange={e=>setOffer(e.target.value)} placeholder="Total offer" className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 outline-none"/></label><button onClick={sendOffer} className="mt-5 w-full rounded-2xl bg-[var(--primary)] p-3 font-semibold text-white">Send quotation</button></>}</div></div>}
 {selectedPayment&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-4 sm:items-center"><div className="w-full max-w-md rounded-[28px] bg-[var(--surface)] p-5"><div className="flex items-center justify-between"><div><small className="text-[var(--muted)]">Payment</small><h3 className="text-xl font-semibold">{selectedPayment.collector}</h3></div><button onClick={()=>setSelectedPayment(null)}><X/></button></div><div className="mt-5 rounded-2xl bg-[var(--surface-soft)] p-4"><small>Amount</small><p className="text-2xl font-semibold">{money(selectedPayment.amount)}</p><p className="mt-1 text-sm text-[var(--muted)]">{selectedPayment.referenceId}</p></div><label className="mt-5 block text-sm font-semibold">Payment method<select value={paymentMethod} onChange={e=>setPaymentMethod(e.target.value)} className="mt-2 w-full rounded-2xl border border-[var(--border)] bg-transparent p-3 outline-none"><option value="">Select method</option><option value="UPI">UPI</option><option value="Cash">Cash</option></select></label><button onClick={makePayment} disabled={!paymentMethod} className="mt-5 w-full rounded-2xl bg-[var(--primary)] p-3 font-semibold text-white disabled:opacity-50">Confirm Payment</button></div></div>}
 {showRates&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-black/40 p-4 sm:items-center"><div className="w-full max-w-lg rounded-[28px] bg-[var(--surface)] p-5"><div className="flex justify-between"><div><h3 className="text-xl font-semibold">Manage buying rates</h3><p className="text-sm text-[var(--muted)]">Update rates for your service area.</p></div><button onClick={()=>setShowRates(false)}><X/></button></div><div className="mt-5 space-y-3">{rates.map(r=><div key={r.id} className="flex items-center justify-between rounded-2xl bg-[var(--surface-soft)] p-3"><b>{r.material}</b>{editing===r.id?<input autoFocus defaultValue={r.price} type="number" onKeyDown={e=>e.key==='Enter'&&saveRate(r.id,e.currentTarget.value)} className="w-24 rounded-xl border p-2"/>:<button onClick={()=>setEditing(r.id)} className="flex items-center gap-2 rounded-xl border bg-[var(--surface)] px-3 py-2">{money(r.price)}/kg <Pencil size={14}/></button>}</div>)}</div><button onClick={()=>setShowRates(false)} className="mt-5 w-full rounded-2xl bg-[var(--primary)] p-3 font-semibold text-white">Save and close</button></div></div>}
 <nav className="fixed bottom-0 left-0 right-0 z-40 border-t border-[var(--border)] bg-[var(--background)]/90 backdrop-blur-xl lg:hidden"><div className="mx-auto flex max-w-lg justify-around p-2">{[['Home',Package,''],['Lots',Package,'marketplace'],['Pickups',Truck,'pickups'],['Payments',Wallet,'payments'],['Profile',UserRound,'']].map(([l,I,id])=><button key={l} onClick={()=>id?document.getElementById(id)?.scrollIntoView({behavior:'smooth'}):l==='Profile'&&navigate('/recycler/settings')} className="flex flex-col items-center gap-1 p-2 text-[var(--muted)]"><I size={19}/><span className="text-[10px]">{l}</span></button>)}</div></nav>
 </div>;
}
